def build_schema_sql(schema: str) -> str:
    return f"""
create schema if not exists {schema};

create table if not exists {schema}.wb_accounts (
    id bigserial primary key,
    account_code text not null unique,
    account_name text not null,
    enabled boolean not null default true,
    token_env_var text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists {schema}.wb_sync_workers (
    id bigserial primary key,
    account_id bigint not null references {schema}.wb_accounts(id) on delete cascade,
    api_type text not null check (api_type in ('orders', 'sales', 'finance_sales_report_details')),
    enabled boolean not null default true,
    schedule_seconds integer not null check (schedule_seconds > 0),
    lookback_days integer not null default 30 check (lookback_days > 0),
    batch_limit integer not null default 80000 check (batch_limit > 0),
    revision integer not null default 1,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (account_id, api_type)
);

create table if not exists {schema}.wb_sync_state (
    account_id bigint not null references {schema}.wb_accounts(id) on delete cascade,
    api_type text not null check (api_type in ('orders', 'sales', 'finance_sales_report_details')),
    cursor_timestamp timestamptz null,
    cursor_key text null,
    last_started_at timestamptz null,
    last_finished_at timestamptz null,
    last_success_at timestamptz null,
    last_error_at timestamptz null,
    last_error_message text null,
    heartbeat_at timestamptz null,
    run_id text null,
    status text null,
    primary key (account_id, api_type)
);

create table if not exists {schema}.wb_sync_runs (
    id bigserial primary key,
    account_id bigint not null references {schema}.wb_accounts(id) on delete cascade,
    api_type text not null check (api_type in ('orders', 'sales', 'finance_sales_report_details')),
    run_id text not null,
    started_at timestamptz not null,
    finished_at timestamptz null,
    status text not null,
    rows_written integer not null default 0,
    error_message text null
);

create index if not exists wb_sync_runs_account_api_idx
    on {schema}.wb_sync_runs (account_id, api_type, started_at desc);

create table if not exists {schema}.wb_orders (
    id bigserial primary key,
    account_id bigint not null references {schema}.wb_accounts(id) on delete cascade,
    record_key text not null,
    order_date timestamptz null,
    last_change_date timestamptz not null,
    warehouse_name text null,
    warehouse_type text null,
    country_name text null,
    oblast_okrug_name text null,
    region_name text null,
    supplier_article text null,
    nm_id bigint null,
    barcode text null,
    category text null,
    subject text null,
    brand text null,
    tech_size text null,
    income_id bigint null,
    is_supply boolean null,
    is_realization boolean null,
    total_price numeric(18,2) null,
    discount_percent numeric(10,2) null,
    spp numeric(10,2) null,
    finished_price numeric(18,2) null,
    price_with_disc numeric(18,2) null,
    is_cancel boolean null,
    cancel_date timestamptz null,
    sticker text null,
    g_number text null,
    srid text null,
    updated_at timestamptz not null default now(),
    unique (account_id, record_key)
);

create index if not exists wb_orders_account_change_idx
    on {schema}.wb_orders (account_id, last_change_date desc);

create table if not exists {schema}.wb_sales (
    id bigserial primary key,
    account_id bigint not null references {schema}.wb_accounts(id) on delete cascade,
    record_key text not null,
    sale_id text null,
    sale_date timestamptz null,
    last_change_date timestamptz not null,
    warehouse_name text null,
    warehouse_type text null,
    country_name text null,
    oblast_okrug_name text null,
    region_name text null,
    supplier_article text null,
    nm_id bigint null,
    barcode text null,
    category text null,
    subject text null,
    brand text null,
    tech_size text null,
    income_id bigint null,
    is_supply boolean null,
    is_realization boolean null,
    total_price numeric(18,2) null,
    discount_percent numeric(10,2) null,
    spp numeric(10,2) null,
    payment_sale_amount numeric(18,2) null,
    for_pay numeric(18,2) null,
    finished_price numeric(18,2) null,
    price_with_disc numeric(18,2) null,
    sticker text null,
    g_number text null,
    srid text null,
    updated_at timestamptz not null default now(),
    unique (account_id, record_key)
);

create index if not exists wb_sales_account_change_idx
    on {schema}.wb_sales (account_id, last_change_date desc);

create table if not exists {schema}.wb_finance_sales_report_details (
    id bigserial primary key,
    account_id bigint not null references {schema}.wb_accounts(id) on delete cascade,
    report_id bigint not null,
    rrd_id bigint not null,
    date_from timestamptz null,
    date_to timestamptz null,
    create_date timestamptz null,
    currency text null,
    report_type integer null,
    gi_id bigint null,
    dlv_prc numeric(18,6) null,
    fix_tariff_date_from timestamptz null,
    fix_tariff_date_to timestamptz null,
    subject_name text null,
    nm_id bigint null,
    brand_name text null,
    vendor_code text null,
    title text null,
    tech_size text null,
    sku text null,
    doc_type_name text null,
    quantity integer null,
    retail_price numeric(18,6) null,
    retail_amount numeric(18,6) null,
    sale_percent numeric(18,6) null,
    commission_percent numeric(18,6) null,
    office_name text null,
    seller_oper_name text null,
    order_dt timestamptz null,
    sale_dt timestamptz null,
    rr_date timestamptz null,
    shk_id bigint null,
    retail_price_with_disc numeric(18,6) null,
    delivery_amount numeric(18,6) null,
    return_amount numeric(18,6) null,
    delivery_service numeric(18,6) null,
    gi_box_type_name text null,
    product_discount_for_report numeric(18,6) null,
    seller_promo numeric(18,6) null,
    spp numeric(18,6) null,
    kvw_base numeric(18,6) null,
    kvw numeric(18,6) null,
    sup_rating_up numeric(18,6) null,
    is_kgvp_v2 integer null,
    ppvz_sales_commission numeric(18,6) null,
    for_pay numeric(18,6) null,
    ppvz_reward numeric(18,6) null,
    acquiring_fee numeric(18,6) null,
    acquiring_percent numeric(18,6) null,
    payment_processing text null,
    acquiring_bank text null,
    vw numeric(18,6) null,
    vw_nds numeric(18,6) null,
    ppvz_office_name text null,
    ppvz_office_id bigint null,
    ppvz_supplier_name text null,
    ppvz_supplier_inn text null,
    declaration_number text null,
    bonus_type_name text null,
    sticker_id text null,
    country text null,
    srv_dbs boolean null,
    penalty numeric(18,6) null,
    additional_payment numeric(18,6) null,
    rebill_logistic_cost numeric(18,6) null,
    rebill_logistic_org text null,
    paid_storage numeric(18,6) null,
    deduction numeric(18,6) null,
    paid_acceptance numeric(18,6) null,
    order_id bigint null,
    kiz text null,
    is_b2b boolean null,
    trbx_id text null,
    installment_cofinancing_amount numeric(18,6) null,
    wibes_discount_percent numeric(18,6) null,
    cashback_amount numeric(18,6) null,
    cashback_discount numeric(18,6) null,
    cashback_commission_change numeric(18,6) null,
    payment_schedule text null,
    delivery_method text null,
    seller_promo_id bigint null,
    seller_promo_discount numeric(18,6) null,
    loyalty_id bigint null,
    loyalty_discount numeric(18,6) null,
    uuid_promocode text null,
    sale_price_promocode_discount_prc numeric(18,6) null,
    article_substitution text null,
    sale_price_affiliated_discount_prc numeric(18,6) null,
    agency_vat numeric(18,6) null,
    sale_price_wholesale_discount_prc numeric(18,6) null,
    order_uid text null,
    srid text null,
    raw_payload jsonb not null,
    updated_at timestamptz not null default now(),
    unique (account_id, report_id, rrd_id)
);

create index if not exists wb_finance_sales_report_details_account_rrd_idx
    on {schema}.wb_finance_sales_report_details (account_id, rrd_id desc);
"""
